### ISSUE TITLE
复选框怎么用js控制不到

### ISSUE THREAD

**Issue by n34n** [easysoft/mzui#12]
复选框怎么用js控制不到开关，好像隐藏掉了，但是界面上在哪里控制

**Comment by catouse** [comment]
MZUI 中的复选框是纯 CSS 实现，当 <input type="checkbox"> 为选中时会自动拥有选中外观，如果需要使用 JS 更改选中状态可以上网搜索下 JS 设置复选框当值（jQuery 方式）。

因为是用法问题，这个 Issue 先关闭了。
