### ISSUE TITLE
不同设备上字体大小相同

### ISSUE THREAD

**Issue by coder-Yin** [easysoft/mzui#2]
不同设备上字体大小相同的问题希望能集成解决

**Comment by catouse** [comment]
谢谢建议。

MZUI 的 CSS 度量单位已经统一为 REM，可以通过 JavaScript 检测设备屏幕尺寸自动更改 body 上的字体大小来调整 UI，以缩放来保持原有尺寸和比例。MZUI 目前并没有默认提供这样的 JS 插件来实现，有以下考虑：
- 不使用缩放则可以使用响应式设计来适配平板设备或者桌面浏览器；
- 开发者实现这样的功能代码量很少，如果制作为通用插件反而变得复杂。

你觉得呢？
