### ISSUE TITLE
提个建议，应该加个文章列表控件。

### ISSUE THREAD

**Issue by cos800** [easysoft/mzui#3]
完整了看了一下官方示例，各种组件应有尽有，
不过唯独没有看到最常用的，文章列表，类似XX头条 XX新闻 各种APP里的都有的新闻资讯列表

**Comment by Catouse** [comment]
参见列表视图：http://zui.sexy/#view/list

**Comment by cos800** [comment]
我说的是 Mzui   手机版的 这个

**Comment by catouse** [comment]
参见 MZUI 控件->列表。
列表控件非常灵活。

**Comment by cos800** [comment]
哦~ 好吧
建议还是在示例中 有所体现，
比如我 想做个资讯类的webapp 看了一下这个列表，
感觉要做出类似XX头条APP的列表效果 会以为还有手写很多CSS。

**Comment by catouse** [comment]
后面会尽量提供更多更丰富的例子。
