### ISSUE TITLE
AjaxForm 冗余处理

### ISSUE THREAD

**Issue by lixinlin** [easysoft/mzui#4]
onSubmit 函数应该增加用户定义函数处理失败以后终止继续提交数据的逻辑，如下：
另外就是选项如果用户已经自定义了函数以后没必要在执行默认逻辑，用户都已经自己处理了，默认逻辑纯属冗余

**Comment by catouse** [comment]
已做如下改进：
- 增加 `onResponse(response, status)` 事件，在该事件回调函数内返回 `false` 将会终止默认处理逻辑；
- 事件 `onSubmit(formData)` 的回调函数中返回 `false`，将会终止这次提交；
- 增加 `dataConverter` 选项，用于指定一个函数来转换或返回需要提交的数据。

**Comment by lixinlin** [comment]
onError事件也需要处理，如果用户定义了onError函数，用户会在onError函数里面进行必要的错误处理，比如提示等，默认的error事件会显示错误信息，这就会跟用户的错误处理发生冲突（用户已经提示了错误信息，结果默认逻辑依然出现错误提示）

**Comment by lixinlin** [comment]
onResponse事件实际上是没必要增加的，onSuccess如果返回false终止默认处理逻辑就行了，多增加一个函数就会增加代码复杂性，没必要，如下修改实际上就可以：
对于onSubmit，返回false，终止提交
对于onSuccess、onError，返回false，终止默认处理逻辑；

对于增加 dataConverter 选项，用于指定一个函数来转换或返回需要提交的数据，这个是个不错的处理

**Comment by catouse** [comment]
谢谢反馈。
