### ISSUE TITLE
文档缺乏

### ISSUE THREAD

**Issue by lixinlin** [easysoft/mzui#5]
文档不细致，使用起来不够方便，另外就是表单组件太小了，应该加大一些

**Comment by easysoft** [comment]
>>>竟然没有文档，网站的示例需要自己通过查看源码的方式了解各个组件的用法，太不人性了，如果不是老手，这玩意真没法使用
你知道维护一个开源产品需要花费多少力气吗？在你轻描淡写的用“**竟然，太不人性化，这玩意**"这些词语来形容mzui之前，你有没有想过你为它做点什么？
