### ISSUE TITLE
iOS端单选框和复选框在选中后，颜色不会改变

### ISSUE THREAD

**Issue by trlanfeng** [easysoft/mzui#7]

**Comment by catouse** [comment]
当复选框和单选框激活是(:focus)时会更改为默认蓝色显示，这个行为在移动端上支持并非完善。

**Comment by catouse** [comment]
<img width="329" alt="2018-01-09 2 12 15" src="https://user-images.githubusercontent.com/472425/34707201-21a02fca-f547-11e7-90d7-73db2ab1c60f.png">
