### ISSUE TITLE
请问有没有未来的更新计划

### ISSUE THREAD

**Issue by easyhuman** [easysoft/mzui#8]
在考虑用mzui，不知道未来更新是否会兼容

**Comment by easyhuman** [comment]
1.0已经发布快一年了，这个项目是否还会更新呢？

**Comment by catouse** [comment]
未来的更新会最大程度考虑兼容，因为我们自己一直在使用这个项目。
目前由于精力有限，所以更新较慢，欢迎提交 pull request。
