### ISSUE TITLE
如果前端展示图片是用underscore模板进行替换过的，能否用图片的点击放大的效果 

### ISSUE THREAD

**Issue by yangjunwu** [easysoft/mzui#9]
目前并不好用 
<script type="text/template" id="tpl_variation">
			<div class="graph4 flex flex-center space-sm">
				<div class="pimg">
					<a data-display="modal" data-target-dismiss="true" data-placement="center" data-content="<img src=<%=PIC_NAME%> alt='' class='no-margin'>">
						<img src="<%=PIC_NAME%>" height="60" width="100%" alt="">
					</a>
				</div>
			</div>
			<p class="small muted pull-center"><%=GENE_VAR%> : <%=VARIATION_SITES%></p>
			</script>
我觉得是不是有些地方没用对，但如果是静态页测试没问题。

**Comment by catouse** [comment]
如果是用 underscore、react、angular 等前端框架，则建议不要使用 MZUI 的 JS 部分。
